#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint

api_login_check:
    path: /api/login_check  